apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testfrontend
  template:
    metadata:
      labels:
        app: testfrontend
    spec:
      containers:
      - name: testfrontend
        image: bakyurek/testfrontend:latest
        ports:
          - containerPort: 7211
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: testfrontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
